### ISSUE TITLE
你好，我按照步骤搭建好了模板之后出现了一个问题。

### ISSUE THREAD

**Issue by WangJunZzz** [ArtechChu/Template#1]
![image](https://user-images.githubusercontent.com/25657426/69134396-615bf000-0af2-11ea-8f70-91c5b4399295.png)
![image](https://user-images.githubusercontent.com/25657426/69134468-7cc6fb00-0af2-11ea-8268-09714603d514.png)
![image](https://user-images.githubusercontent.com/25657426/69134501-86e8f980-0af2-11ea-8cdd-c0a42fb2d83a.png)
![image](https://user-images.githubusercontent.com/25657426/69134519-8d777100-0af2-11ea-98ef-73e838699276.png)
然后执行dotnet new -i Fairhr.WebApi得时候报错。

**Comment by ArtechZhu** [comment]
你好，从你的错误信息中看是 .NET CORE 版本导致的错误，可以尝试在 dotnet new 命令后面指定netcoreapp版本，如： -f  netcoreapp1.0
具体.NET CORE 版本请根据自己的项目来指定，以上为指定版本为1.0

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/69135466-180ca000-0af4-11ea-9496-eac16cd5d335.png)

没有这个参数

**Comment by ArtechZhu** [comment]
请选确保下是否有安装你需要netcore版本，如2.1，2.2。我这边测试了下，直接看选项的话确实没有公布，但是在你显式指定 -f 选项时候，若报错，会提示你（包括你本机已经安装的netcore SDK，见下图，我本机安装有netcore 2.1和3.0），指定后是没有问题的（如我这边测试是安装 console）。
另外需要确保下，不同版本的visualt studio，对 netcore SDK 版本是有要求的，见连接：[https://dotnet.microsoft.com/download/visual-studio-sdks?utm_source=getdotnetsdk&utm_medium=referral](https://dotnet.microsoft.com/download/visual-studio-sdks?utm_source=getdotnetsdk&utm_medium=referral)，请确保均无问题。
![image](https://user-images.githubusercontent.com/3915949/69138312-64a6aa00-0af9-11ea-9f3c-f69020b16245.png)

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/69139484-93be1b00-0afb-11ea-9214-7fa69d48e627.png)
![image](https://user-images.githubusercontent.com/25657426/69139618-d4b62f80-0afb-11ea-86a2-d23e3a42194a.png)
![image](https://user-images.githubusercontent.com/25657426/69139654-e8fa2c80-0afb-11ea-9132-7dbc5cbc84d3.png)

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/69139951-88b7ba80-0afc-11ea-85b6-5c7a4bbaeb4d.png)
![image](https://user-images.githubusercontent.com/25657426/69139991-99683080-0afc-11ea-835d-da9b9c78e9f5.png)
怎么突然报没有这个，nuget上有。其实我在生成在本地是可以，但是发布到私有nuget服务器上就不行，我还以为是私有服务器得版本问题，发现也是.net core3.0.100

**Comment by ArtechZhu** [comment]
dotnet new -i XXX 是安装 XXX 这个模板，这个命令没有 -f 选项。
dotnet new XXX 是适用XXX这个模板生成对应的XXX项目，这个是有 -f 选项。
另外确认下在上传前生成的模板是否是对应 dotnet core 版本，有一个简单的方法是你只创建一个项目（如classlib），然后把他做成模板，本地/上传到nuget安装看是否可行：）

**Comment by WangJunZzz** [comment]
类库什么得都没问题，之前做过了。
![image](https://user-images.githubusercontent.com/25657426/69202443-a593d280-0b7c-11ea-9fb9-ccbc0566f3c2.png)
头痛了 3.0 来这个
https://github.com/OrchardCMS/OrchardCore/issues/4477

**Comment by WangJunZzz** [comment]
之前上传过.net standard2.0的类库到nuget上没有问题。
![image](https://user-images.githubusercontent.com/25657426/69203352-058b7880-0b7f-11ea-9e90-06acbe576bef.png)
3.0d的问题这么多的嘛？

**Comment by WangJunZzz** [comment]
把你的代码拉取下来是可以，但是我按照同样的模板3.0就不行。

**Comment by ArtechZhu** [comment]
很抱歉，3.0我没有尝试过，后续项目中用到3.0的时候，我会再更新下：）

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/69228246-33dc7880-0bbe-11ea-9ff7-84b6f40f27a2.png)
琢磨了一天，好不容易不报错，但是dotnet new -l 没有这个。。。

**Comment by WangJunZzz** [comment]
https://github.com/WangJunZzz/Fairhr.WebApi
我放到这个上面了，大佬，有时间帮我看看是什么原因吗？

**Comment by WangJunZzz** [comment]
不要发布到nuget.org上面了。。 。哈哈

**Comment by WangJunZzz** [comment]
今天早上就可以dotnet new -i了  神奇。

**Comment by ArtechZhu** [comment]
当实在搞不定的时候，尝试重启系统 or 重启 VS，一般会有惊喜：P

**Comment by WangJunZzz** [comment]
哈哈 谢谢大佬的解惑。
